### ISSUE TITLE
I can not detect all the circles with Android Camera

### ISSUE THREAD

**Issue by MedOussama** [ahmetozlu/real_time_circle_detection_android#1]
Hello,

I need to detect circles taken with their positions X Y, I want to use this data to compare them with the original image to retrieve an ID. It's like the principle of QR Code.

I want to create a system like Snapcode (snapchat)

We want scan like this picture https://ibb.co/gMkEJd with the Android Camera

Cordially,

**Comment by ahmetozlu** [comment]
[Circle Hough Transform](https://en.wikipedia.org/wiki/Circle_Hough_Transform) was used to detect circles in the [project](https://github.com/ahmetozlu/real_time_circle_detection_android) so you can detect the circles which are suitable to detect by [Circle Hough Transform](https://en.wikipedia.org/wiki/Circle_Hough_Transform). Of course, there are tons of other parameters that effect detection performance such as: 
- camera resolution
- lightning
- shadows
- reflections
- circle size

And, please be careful about your device camera capabilities and also about the environment that should be convenient to detect circles (for example with suitable lightning without reflections and shadow)...

You can improve the detection performance by:
- configuring the auto focus feature of Android camera
- pre-filtering such as sharpening (for example using [Canny Edge Detector](https://en.wikipedia.org/wiki/Canny_edge_detector)) the frames before sending the frames to detection system
- increase the size of each frame by 2 for making circles bigger (usually, it is easier detecting of bigger circles than detecting of little circles)

I checked the image you shared, also I recommend you to try "[Blob Detection](https://en.wikipedia.org/wiki/Blob_detection)", here is a [nice tutorial](https://www.learnopencv.com/blob-detection-using-opencv-python-c/) about it. You can detect all the blobs that will be the possible circles you would be interested and then you can get their center positions to use them in your calculations.
